package com.myspace.hotel;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class AvailableParkingLots implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer availableParkingLotsCount;

	public AvailableParkingLots() {
	}

	public java.lang.Integer getAvailableParkingLotsCount() {
		return this.availableParkingLotsCount;
	}

	public void setAvailableParkingLotsCount(
			java.lang.Integer availableParkingLotsCount) {
		this.availableParkingLotsCount = availableParkingLotsCount;
	}

	public AvailableParkingLots(java.lang.Integer availableParkingLotsCount) {
		this.availableParkingLotsCount = availableParkingLotsCount;
	}

}