package com.myspace.hotel;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.xml.bind.annotation.XmlRootElement
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CUSTOMER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "CUSTOMER_ID_SEQ", name = "CUSTOMER_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Surname")
	private java.lang.String surname;

	@org.kie.api.definition.type.Label("First Name")
	private java.lang.String firstName;

	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "Phone number")
	private java.lang.String phone;

	public Customer() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public Customer(java.lang.Long id, java.lang.String surname,
			java.lang.String firstName, java.lang.String email,
			java.lang.String phone) {
		this.id = id;
		this.surname = surname;
		this.firstName = firstName;
		this.email = email;
		this.phone = phone;
	}

}