package com.myspace.hotel;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Issue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Short Description")
	private java.lang.String short_description;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "Time Commitment (in hours)")
	private java.lang.Float time;

	public Issue() {
	}

	public java.lang.String getShort_description() {
		return this.short_description;
	}

	public void setShort_description(java.lang.String short_description) {
		this.short_description = short_description;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Float getTime() {
		return this.time;
	}

	public void setTime(java.lang.Float time) {
		this.time = time;
	}

	public Issue(java.lang.String short_description,
			java.lang.String description, java.lang.Float time) {
		this.short_description = short_description;
		this.description = description;
		this.time = time;
	}

}